### ISSUE TITLE
EmergencySTOPが割り込み動作しない

### ISSUE THREAD

**Issue by ghost** [dinosauria123/StacKlipper#2]
処理中の動作の後にM112が実行される
例えば、ホーミング中にEmergencySTOPを押してもホーミングが終わるまで緊急停止しない。
Stacklipper.ino208行目の
`command = "printer/gcode/script?script=M112";`
を
`command = "printer/emergency_stop";`
と書けば割り込んで動作するようになるので、緊急停止ボタンとして正しく機能します。

**Comment by dinosauria123** [comment]
コメントありがとうございます！修正しました！
